### ISSUE TITLE
Document the openapi.yml file

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial#29]
Our API is specified in Open API format (formerly known as Swagger.)

We need to fully document this API. Right now, I've basically added a short summary for every item in there.

The OpenAPI specification allows for rich documentation (including examples, long descriptions, etc.) We want to take advantage of this as much as we can.

**Comment by erikth23** [comment]
I can work on this

**Comment by svpino** [comment]
Right now the API is changing a lot. It's normal; we are designing and thinking about it as we go. (I just made a change that wasn't there when you looked at it yesterday.)

I'm tracking what I want the API to have on this issue: https://github.com/underfitted/bnomial/issues/24

The "immediate future state" is there, while the `openapi.yml` file has the current implementation.

My recommendation is that you start with `openapi.yml` and then move to [the specification](https://github.com/underfitted/bnomial/issues/24) and add your comments on that issue.
